### ISSUE TITLE
Is this repo alive?

### ISSUE THREAD

**Issue by ecarreras** [transifex/transifex-old-core#206]
This repo seems dead, the last commit is from 7 months ago, and it only adds a new language... I see that transifex.com is so differnt from the version of this repo? Seriously all the development of transifex is done here?

The release cycle[1] is also outdated, the last version that I can see is 1.2.1 [2]

We can see the repo network[3], and there is some people doing commits and working on it. Some of they are:

@pejakm @fazakis @tymofij @soslan @Lockal

Why not create a main community edition fork? and send back pull-requests to official transifex repo?

[1] http://help.transifex.com/server/releases/index.html#transifex-releases
[2] http://help.transifex.com/server/releases/1.2.html#transifex-ce-1-2-1
[3] https://github.com/transifex/transifex/network

**Comment by GreenLunar** [comment]
Open source seems to work just great for WordPress (wordpress.,org - software; wordpress.com - ads/pay service).  But making your software closed, after gaining popularity - some due to being open-sourced, is your choice.  Anyhow, I really don't care. I am displeased of helping - a small fraction, though - transifex.net to be more relevant.

**Comment by kfogel** [comment]
I appreciate the care you put into the above explanation, but if the decision was truly engineering-driven and not business-driven, then why not just host your entire repository out in the open with an open source license?

In other words, the fact that you "ended up spending more time working on loosely-coupling everything than actually working on useful features for the users" was due to your own decision to separate the code into a public version and a private version in the first place.  If you wanted to reduce the engineering overhead, just move the private stuff -- yes, the stuff that's "only useful for big, paying companies such as deep analytics on the TM usage per user etc" -- out into the public repository.

After all, the main reason people cared that your repository was open source was not that they wanted to host their own version, but that they wanted to know that _they could do so if they ever had to_.  In other words, that they had the freedoms that come with open source.  It's okay if your public repository is primarily useful to you, and isn't so easy for outside developers to get involved in.  No one, at least no one who has ever run a software product business themselves, would insist that you take on the overhead of community management and modularization.  Everyone understands that you have to make the product work for your customers.

But that's no reason to make it closed source.  Unless you're using proprietary libraries as part of the code now, there is literally no code change your developers could commit to the current closed, proprietary repository that they couldn't just as easily commit to a public repository.  After all, it's just one line in .git/config, right?  Everything else stays the same.

So I don't understand the statements that "The decision was engineering-driven, not business-driven" or "We had no issue whatsoever with our competitors looking at our code. On the contrary, it gave us a huge edge and confidence with our customers they could never have had."  If this is still true, then why not do everything you're doing now, but just in an open source repository?

Or if those statements aren't still true, then just say so :-).  From here, it really looks like a business-driven decision, unless I'm missing something...

@sembrestel's point about the [pending patent](http://www.prweb.com/releases/2014/10/prweb12226960.htm) is relevant too.  Let me ask directly: what would Transifex do if another project (whether open source or not) used the same technique covered in the patent as part of their own translation platform software?  Would you enforce the patent, i.e., file an infringement claim?

I want to recommend Transifex, but it is harder to do so now that the platform is no longer open source.  If the explanation for _why_ the platform is no longer open source were at least internally consistent, that would at least make things less confusing.

Sincerely,
-Karl

**Comment by d3netxer** [comment]
+1 Karl

**Comment by strk** [comment]
+1 Karl

**Comment by glezos** [comment]
Writing this 2.5 years after the original comment. Wow, time flies, doesn't it.

There's a core decision to keep some parts of the Transifex.com code-base non open-source. There has always been a non open-source component to the Transifex.com code-base. Since day 1. Here are a few examples that come into mind right now:

* The distinctive design, look-and-feel of Transifex.com
* Paid subscriptions, quota management of accounts. Notification system related to these.
* Ordering professional translations from external agencies. Features to work with your own professional agencies inside Transifex. Agency dashboards, analytics for SLAs. Translation Memory leverage groups.
* Integrations with other internal services to our company such as sales, marketing, support and other systems.
* Deep analytics and business intelligence to track the success path of users, used to improve the user experience. Internal dashboards.
* Infrastructure integrations with services such as Rackspace Cloud, Amazon Redshift, New Relic etc.
* Built-in referral program with subscription discount
* Delivery component of Transifex Live (CDN) and analytics 

There are lots of reasons to keep these components non open-source. It makes sense for us for all kind of areas, including engineering, operations and business.

In the beginning, when the number of the components were a couple and the codebase small, we were able to maintain a working open-source repository next to the core one which included the above. After a while, it was very hard to keep maintaining this split and we chose to focus our efforts in other parts.

The truth is, another company might have made the choice to search for the resources somehow to continue maintaining both repos. Maybe that company would have succeeded to do so, or maybe it would have failed and closed down.

I understand that some of the above disappoint some of you. There are other options. If having the ability to host your own translation system is a blocker to you, we recommend using [Pootle](http://pootle.translatehouse.org/) or [Weblate](https://weblate.org). Hundreds of projects and companies are using them successfully.

In the meantime, we're committed to continue offering Transifex for [free to open-source projects](https://www.transifex.com/customers/open-source/).

**Comment by kfogel** [comment]
Thanks, @glezos.  I think you might be mostly answering a different question to the ones raised (at least the ones raised in recent comments).  The point I was making was that it's better for everyone if Transifex is up-front about its reasons.  I wasn't arguing with going closed-source as a business decision, I was just saying that if it _is_ a business decision to call it a business decision.  The original reasoning given in this ticket didn't really make sense -- and was different from the reasoning you give above :-).

You don't address the question about the patent.

**Comment by strypey** [comment]
@kfogel Maybe the Transifex commitment to "open source" was always a commitment to the [GH model of "open source"](http://tom.preston-werner.com/2011/11/22/open-source-everything.html)? Keep the really significant stuff proprietary, to allow user lock-in (instead of "like-in"), but release all the trivial code that gaffer tapes it all together, so you can leverage the unpaid work of developers in the community to patch your sloppy, prototype code for you, and attract priceless unpaid promotion work from the community, who are always willing to give the benefit of the doubt to new projects ([Qwant is a more recent example of this](https://help.qwant.com/help/overview/how-to-contribute-to-qwants-open-source-projects/)). It's a cynical, extractive model (one people like me and Red Hat have criticized as "[open core](https://www.redhat.com/en/blog/open-source-or-open-core-why-should-you-care)" although [use of this phrase is being discouraged](http://ebb.org/bkuhn/blog/2011/03/05/open-core-slur.html) in some quarters), and although encouraging greater use of strong copyleft licenses makes it harder to get away with, if the company does a Canonical and uses Contributor License Agreements to claim any and all rights to engage in "proprietary relicensing", they can still use work donated to a free code project in proprietary products, with or without releasing that code in a free code version.

Just to be clear, I'm not opposed to "[selling exceptions](https://www.gnu.org/philosophy/assigning-copyright)" to copyleft, where it means redirecting money into funding free cod dev that would otherwise be spent licensing proprietary software (the [Commons Management Agreement](https://www.clahub.com/agreements/cjdelisle/cryptpad) that X-Wiki Labs use for this seems legit). I also think there are cases where proprietary relicensing is done is that spirit - GitLab seem pretty genuine in their motives and [regularly move code from their EE to their CE in response to developer feedback](https://news.ycombinator.com/item?id=10923379)) - so it's not a cut-and-dried thing. Maybe Transifex started out planning to be like GitLab, but their management got hijacked by some business consultant who doesn't understand the political economy of peer production, and just assumes that making the source code into secret sauce ("controlling the IP") magically makes it more profitable?

[AlternativesTo has a list of open source replacements for Transifex](https://alternativeto.net/software/transifex/?license=opensource). It would be useful to gather feedback from everyone who's evaluated any of them, or any others missing from the list, about which one are completely free code stacks, and which ones are free code gaffer tape wrapped around proprietary business logic.
